// --- PASTE YOUR SUPABASE KEYS HERE ---
const SUPABASE_URL = 'https://joreuafteizcymsdwmcl.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvcmV1YWZ0ZWl6Y3ltc2R3bWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4NjA4NjEsImV4cCI6MjA3NTQzNjg2MX0.N0mw8mmw3f5AoKcKPFmUbksHwzlNAQaUuVKqgN1rb2U';
